### ISSUE TITLE
getAllSets() of some tournaments causes memory problems

### ISSUE THREAD

**Issue by L3mmAa** [BrandonCookeDev/smashgg.js#33]
When i try to get all GGSets of certain tournaments i get a Javascript heap of of memeory error.
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```
One of those tournaments is https://smash.gg/tournament/net-battle-series-5/events/ultimate-singles/brackets/512334/879036.

I dont think this actually is a memory problem, in a way that there are too many GGSets loaded into memory because i can load GGSets from much bigger tournaments with no problem.

If it helps, my code looks like this:
```
for (var n = 0; n < slugs.length; n++) {
        let tournament = await Tournament.getTournament(slugs[n]);
        let sets = await tournament.getCompleteSets();
        console.log(sets.length);
    }
```

**Comment by BrandonCookeDev** [comment]
I'll dig into this and get back to you soon.

**Comment by BrandonCookeDev** [comment]
I created a small sandbox environment and ran getCompleteSets on your example bracket and didn't run into anything so far. Here are some screenshots, maybe you can help guide me toward your specific use case:
--------
![image](https://user-images.githubusercontent.com/10892126/51537645-13685400-1e1d-11e9-835b-80f2e0ff7590.png)

![image](https://user-images.githubusercontent.com/10892126/51537648-16634480-1e1d-11e9-9b54-13cd56246e1f.png)

![image](https://user-images.githubusercontent.com/10892126/51537651-18c59e80-1e1d-11e9-93b5-7199b7f409e3.png)

![image](https://user-images.githubusercontent.com/10892126/51537653-1bc08f00-1e1d-11e9-8a44-51a4bb759ded.png)

**Comment by L3mmAa** [comment]
I have a large list of slugs, here is a part of it for testing if you need it: https://pastebin.com/2pEN6m3S
My code look slike this:
```
async function scrape() {
    for (var n = 0; n < slugs.length; n++) {
        try {
            let tournament = await Tournament.getTournament(slugs[n]);
            let sets = await tournament.getAllSets();
            console.log(sets.length);
        } catch {}
    }
    console.log('all done');
```
If i use this function i cant cycle through all the slugs (in the list above) without getting memory problems. I hope that helps.

Strange thing is that the original tournament now doesnt give me errors today, but others do.

**Comment by BrandonCookeDev** [comment]
It is possible that the cache is being overflown.
Try this and see what happens?

```javascript
for (var n = 0; n < slugs.length; n++) {
        try {
            let tournament = await Tournament.getTournament(slugs[n], {isCached: false});
            let sets = await tournament.getAllSets();
            console.log(sets.length);
        } catch {}
    }
```

**Comment by BrandonCookeDev** [comment]
I tried the following to make a reproduce-case, but non of these error'd because of heap space

```javascript
(async function(){
    /** Put your sandbox code here */
    let slugs = [
        'to12', 
        'ceo-2016', 
        'ceo-2017', 
        'ceo2018', 
        'evo-2017', 
        'evo-2018'
    ];

    let counter = 0;
    for(var i in slugs){
        try{
            let slug = slugs[i];
            let t = await Tournament.getTournament(slug);
            let sets = await t.getAllSets();
            console.log(sets);
            console.log('---------------')
            counter++
            console.log(`Got ${counter}/${slugs.length} tournament sets`)
        } catch(e){
            console.error(e);
        }
    }
    
})()
```

**Comment by L3mmAa** [comment]
Did you try the slugs in the list i provided above? (https://pastebin.com/2pEN6m3S) It crashes for me if i use them.

**Comment by BrandonCookeDev** [comment]
Oh I totally missed that link. Apologies.
I'll use that on my next debugging session.

**Comment by BrandonCookeDev** [comment]
Just to update you, I plan on implementing a series of updates using the new GQL API, and getting sets is one of those. 

Just curious did you ever try while setting the Cache option to `false`?

**Comment by L3mmAa** [comment]
Yeah i tried setting it to false but it didnt do anything. 

The workaround im using right know is that i first get the events of the tournament, then get the phases of the event, then get the phasegroups of the phase. The phasegroup object then has the sets stored in a array.

**Comment by BrandonCookeDev** [comment]
@L3mmAa Please try using the new SDK version.
Keep in mind the rate limit, however. It won't be quick but should be consistent.

**Comment by BrandonCookeDev** [comment]
@L3mmAa due to complications with the way gg is rate limiting, Tournaments have had their `getAllSets` removed from the newest versions of the SDK. Unless you're attempting to pull specific events, I don't believe I have the bandwidth to fix this issue in V1.

I'm open to ideas however.
