### ISSUE TITLE
CORs error from smashgg

### ISSUE THREAD

**Issue by flemings** [BrandonCookeDev/smashgg.js#36]
Hi, I am getting a CORs error from smash.gg itself. Do I need to add headers to the request to make it work? I tried 'mode':'no-cors'. Currently I am testing from localhost. Any help would be appreciated, thanks!

![image](https://user-images.githubusercontent.com/14184054/52682602-445c1600-2efd-11e9-80ff-379c0526b492.png)

**Comment by BrandonCookeDev** [comment]
Hi! Smashgg historically never offered CORS on their version 1 API. It was a large issue, and means that you cannot use smashgg.js on the frontend.

However, another dev and I made a package just for you!
https://github.com/BrandonCookeDev/smashgg-promise

This is a frontend-capable library that leverages an AWS Lambda function to pad on the CORS headers. Also try looking into their new API @ https://smashgg.zendesk.com/hc/en-us/articles/217471947-API-Access

They implemented GraphQL recently and should have handled CORS in this. Smashgg.js is undergoing an overhaul to ingest this new API and **WILL** have CORS capability. Please keep in mind when using smashgg-promise, and it will probably be sunset a few months after this package is updated.

**Comment by flemings** [comment]
Thanks! Will you guys be maintaining the same function signatures? e.g. Event.getEvent(...) Or will this a complete overhaul?

**Comment by BrandonCookeDev** [comment]
The general functionality of this package will not be changing with the overhaul. Everything you're interfacing with now will be there in V4; however they may be named differently as to adhere to a more consistent standard (ie. `Event.getEventSets()` will become `Event.getSets()` and etc)
