### ISSUE TITLE
Require Module Error

### ISSUE THREAD

**Issue by An78toi13ne06** [BrandonCookeDev/smashgg.js#44]
I was trying to use this lib for my project with smashgg API.
I recently had to reinstall the entire project inclusing this lib.
But with the last update I have an strange error :
`PS C:\\*\*\GitHub\smashgg-attendees-counter> node .\index.js
internal/modules/cjs/loader.js:716
    throw err;
    ^

Error: Cannot find module './src/v4/js'
Require stack:
- C:\\*\*\GitHub\smashgg-attendees-counter\node_modules\smashgg.js\index.js
- C:\\*\*\GitHub\smashgg-attendees-counter\index.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:713:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:618:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:771:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:68:18)[39m
    at Object.<anonymous> (C:\\*\*\GitHub\smashgg-attendees-counter\node_modules\[4msmashgg.js[24m\index.js:1:18)
[90m    at Module._compile (internal/modules/cjs/loader.js:868:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:731:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:644:12)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:771:19)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'C:\\\*\*\\GitHub\\smashgg-attendees-counter\\node_modules\\smashgg.js\\index.js'[39m,
    [32m'C:\\\*\*\\GitHub\\smashgg-attendees-counter\\index.js'[39m
  ]
}`

For me it means that /src/v4/js doesn't exist and in fact I can't find it in the node_module folder:
![image](https://user-images.githubusercontent.com/17361604/62689179-9e302b00-b9ca-11e9-9b0b-aae57e235959.png)

What can I do to solve this problem ? Thks

**Comment by BrandonCookeDev** [comment]
Hey @An78toi13ne06 
I accidentally broke this on a deployment error. 

I've deprecated these versions and fixed it in the most recent versions > 4.1.3
Please update and try again, and sorry for the inconvenience! I've created a bunch of Devops scripts this morning to ensure this incident never happens again.

**Comment by BrandonCookeDev** [comment]
additionally, upon inspection this issue affects 4.1.2 and 4.1.3
I've deprecated both versions

**Comment by An78toi13ne06** [comment]
Sorry for the late answer.
Every thing came back to normal.
Closing the issue.
