### ISSUE TITLE
Error in function GetEvents from a Tournament

### ISSUE THREAD

**Issue by Dannolo** [BrandonCookeDev/smashgg.js#54]
https://github.com/BrandonCookeDev/smashgg.js/blob/344fd72ec1e58ebaee03bb7dbea60dfbe578c8b2/src/v4/ts/lib/scripts/tournamentQueries.ts#L105

Hi, just found out that the problem in this function for getEvents() from a Tournament is the **":"** in the query. Just delete it.
           
`export const tournamentEvents = query TournamentEvents($id: ID!){
    tournament(id: $id){
        events{
            ${Schema.event}
        }
    }
}`

**Comment by BrandonCookeDev** [comment]
Fixed by ebe5b9b
